global:
  scrape_interval: 15s # Alle 15 Sekunden Daten holen

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hier verbinden wir uns mit deinem CATALOG Service
  - job_name: 'catalog-service'
    metrics_path: '/actuator/prometheus' # Pfad anpassen (siehe Hinweis unten*)
    static_configs:
      - targets: ['catalog:8080'] # Service-Name aus docker-compose

  # Hier verbinden wir uns mit deinem ORDER Service
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus' # Pfad anpassen (siehe Hinweis unten*)
    static_configs:
      - targets: ['order:8081'] # Service-Name aus docker-compose